const SUPABASE_URL = process.env.SUPABASE_URL
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY
const PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY
const ADMIN_EMAILS = (process.env.ADMIN_EMAILS || '').split(',').map(s => s.trim().toLowerCase()).filter(Boolean)
function json(res,status,body){res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.end(JSON.stringify(body))}
async function sb(path,options={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`,'Content-Type':'application/json',Prefer:'return=representation',...(options.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.hint||d?.error||t||`Supabase HTTP ${r.status}`);return d}
async function currentUser(token){const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${token}`}});if(!r.ok)return null;return r.json()}
async function auth(req){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim();if(!token)return null;const user=await currentUser(token);if(!user)return null;const role=user.app_metadata?.role;const roles=user.app_metadata?.roles||[];if(role==='admin'||roles.includes('admin')||ADMIN_EMAILS.includes(String(user.email||'').toLowerCase()))return user;return null}
const tables={products:['id','sku','slug','name','description','short_description','category','origin_country_code','catch_area','processing_type','storage_temperature_c','is_frozen','status','image_url','gallery','is_top_product','is_on_sale','sale_price','sale_from','sale_until'],product_variants:['id','product_id','sku','name','net_weight_kg','gross_weight_kg','units_per_case','min_order_qty','order_qty_step'],packagings:['id','code','name','description','units_per_package','tare_weight_kg'],customer_segments:['id','code','name','description','is_active'],companies:['id','legal_name','trading_name','registration_number','vat_number','country_code','email','phone','status','customer_segment_id'],price_lists:['id','code','name','currency','customer_segment_id','valid_from','valid_until','is_active'],price_list_items:['id','price_list_id','product_variant_id','packaging_id','unit_price','currency','min_qty','max_qty'],customer_price_overrides:['id','company_id','product_variant_id','packaging_id','unit_price','currency','min_qty','max_qty','valid_from','valid_until','discount_percent'],moq_rules:['id','product_variant_id','customer_segment_id','min_qty','qty_step'],product_promotions:['id','product_id','title','promotion_type','sale_price','discount_percent','starts_at','ends_at','is_active'],product_media:['id','product_id','media_type','url','alt_text','sort_order','is_primary']}
function clean(table,row){const allowed=tables[table];return Object.fromEntries(Object.entries(row||{}).filter(([k,v])=>allowed.includes(k)&&k!=='id'&&v!==undefined))}
export default async function handler(req,res){if(!SUPABASE_URL||!SERVICE_KEY||!PUBLISHABLE_KEY)return json(res,500,{error:'Admin API is not configured'});if(!['GET','POST','DELETE'].includes(req.method))return json(res,405,{error:'GET, POST or DELETE required'});try{const user=await auth(req);if(!user)return json(res,401,{error:'Admin authentication required'});const body=typeof req.body==='string'?(req.body?JSON.parse(req.body):{}):(req.body||{});const url=new URL(req.url,'http://localhost');const table=String(body.table||url.searchParams.get('table')||'');if(!tables[table])return json(res,400,{error:'Unsupported admin table'});if(req.method==='GET'){const limit=Math.min(Number(url.searchParams.get('limit')||100),500);return json(res,200,await sb(`${table}?select=${encodeURIComponent(tables[table].join(','))}&limit=${limit}`))}if(req.method==='DELETE'){if(!body.id)return json(res,400,{error:'id required'});return json(res,200,await sb(`${table}?id=eq.${encodeURIComponent(body.id)}`,{method:'DELETE'}))}const row=clean(table,body.row);if(!Object.keys(row).length)return json(res,400,{error:'row required'});if(table==='customer_price_overrides'&&body.row?.id)return json(res,200,await sb(`customer_price_overrides?id=eq.${encodeURIComponent(body.row.id)}`,{method:'PATCH',body:JSON.stringify(row)}));const conflict={products:'sku',customer_segments:'code',price_lists:'code',packagings:'code',product_variants:'sku'}[table];const path=conflict?`${table}?on_conflict=${conflict}`:table;return json(res,200,await sb(path,{method:'POST',body:JSON.stringify(row),headers:{Prefer:`return=representation${conflict?',resolution=merge-duplicates':''}`}}))}catch(e){console.error(e);return json(res,500,{error:e instanceof Error?e.message:String(e)})}}
